import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-title-insurance-closing-fee-audit",
  "engine": "recovery",
  "title": "Title Insurance & Closing Fee Audit",
  "shortTitle": "Title Insurance and Closing Fee Audit",
  "tagline": "Quantify, recover, and prevent financial leakage through title insurance & closing fee audit",
  "industry": "Real Estate Closing Cost Recovery",
  "uiPort": 4617,
  "apiPort": 5617,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "Title Insurance & Closing Fee Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged Closing Costs",
    "expectedLabel": "Rate-Supported Costs",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Title Insurance & Closing Fee Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("state-title-rate-library","TIC01","State title rate library","Execute state title rate library using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed state title rate library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","State title rate library Reference","text","TIC01-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("transaction-property-registry","TIC02","Transaction property registry","Execute transaction property registry using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed transaction property registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Transaction property registry Reference","text","TIC02-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("loan-purchase-ingestion","TIC03","Loan purchase ingestion","Execute loan purchase ingestion using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed loan purchase ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Loan purchase ingestion Reference","text","TIC03-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("owner-policy-calculation","TIC04","Owner policy calculation","Execute owner policy calculation using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed owner policy calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Owner policy calculation Reference","text","TIC04-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("lender-policy-calculation","TIC05","Lender policy calculation","Execute lender policy calculation using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed lender policy calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Lender policy calculation Reference","text","TIC05-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("simultaneous-issue-rate","TIC06","Simultaneous issue rate","Execute simultaneous issue rate using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed simultaneous issue rate decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Simultaneous issue rate Reference","text","TIC06-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("reissue-refinance-credit","TIC07","Reissue refinance credit","Execute reissue refinance credit using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed reissue refinance credit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Reissue refinance credit Reference","text","TIC07-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("endorsement-validation","TIC08","Endorsement validation","Execute endorsement validation using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed endorsement validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Endorsement validation Reference","text","TIC08-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("search-examination-fee-audit","TIC09","Search examination fee audit","Execute search examination fee audit using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed search examination fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Search examination fee audit Reference","text","TIC09-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("recording-fee-reconciliation","TIC10","Recording fee reconciliation","Execute recording fee reconciliation using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed recording fee reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Recording fee reconciliation Reference","text","TIC10-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("transfer-tax-calculation","TIC11","Transfer tax calculation","Execute transfer tax calculation using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed transfer tax calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Transfer tax calculation Reference","text","TIC11-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("settlement-fee-audit","TIC12","Settlement fee audit","Execute settlement fee audit using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed settlement fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Settlement fee audit Reference","text","TIC12-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("closing-disclosure-comparison","TIC13","Closing disclosure comparison","Execute closing disclosure comparison using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed closing disclosure comparison decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Closing disclosure comparison Reference","text","TIC13-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("refund-package","TIC14","Refund package","Execute refund package using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed refund package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Refund package Reference","text","TIC14-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]}),
feature("agent-jurisdiction-analytics","TIC15","Agent jurisdiction analytics","Execute agent jurisdiction analytics using state title rates, properties, loans, purchase prices, owner and lender policies, simultaneous issue, reissue credits, endorsements, recording fees, transfer taxes, disclosures, and refunds.","Produce a governed agent jurisdiction analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Title Agent / Closing","text","Title Agent / Closing · Standard Case"],["caseReference","Agent jurisdiction analytics Reference","text","TIC15-2026-001"],["chargedAmount","Charged Closing Costs","currency",901000],["supportedAmount","Rate-Supported Costs","currency",774860],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["State title rate library case","Transaction property registry case","Loan purchase ingestion case","Owner policy calculation case","Lender policy calculation case"]})
]);
